### ISSUE TITLE
Assertion for auditd_space_left contradicts what's written in the README

### ISSUE THREAD

**Issue by nono-lqdn** [buluma/ansible-role-auditd#24]
If you look at https://github.com/buluma/ansible-role-auditd/blob/c6d3b62bc0035479bdf984fcbf46378c4d693d94/tasks/assert.yml#L168, you will see that the assertion for `auditd_space_left` contradicts what's written in the README. 

It's written that it can be 

> `auditd_space_left: "75"`  # This can be a number ('25') or a percentage. ('25%')

But actually, if you write a percentage, then it's a string, but the assertion checks that it's a number. 

The audtid.conf(5) manual says that ; 

>   space_left
>              If the free space in the filesystem containing log_file
>               drops below this value, the audit daemon takes the action
>               specified by space_left_action.  If the value of
>               space_left is specified as a whole number, it is
>               interpreted as an absolute size in megabytes (MiB).  If
>               the value is specified as a number between 1 and 99
>               followed by a percentage sign (e.g., 5%), the audit daemon
>               calculates the absolute size in megabytes based on the
>               size of the filesystem containing log_file.  (E.g., if the
>               filesystem containing log_file is 2 gigabytes in size, and
>               space_left is set to 25%, then the audit daemon sets
>               space_left to approximately 500 megabytes.  Note that this
>               calculation is performed when the audit daemon starts, so
>               if you resize the filesystem containing log_file while the
>               audit daemon is running, you should send the audit daemon
>               SIGHUP to re-read the configuration file and recalculate
>               the correct percentage.

Thus, the assertion should check that it's 

- A number, between 0 and the maximum int value. 

OR

- A string, containing a value between 0 and 99, ending with '%'.

Currently, it's only possible for the role to specify a value in MB between 0 and 100.

The code should be something like this : 
```

- name: assert | Test auditd_admin_space_left
  ansible.builtin.assert:
    that:
      - auditd_admin_space_left is defined
      - auditd_admin_space_left is number or  auditd_admin_space_left is string 
      - auditd_admin_space_left is match("([0-9])%*")
    quiet: true
```

**Comment by nono-lqdn** [comment]
Actually, it's a bit different. It's not `auditd_admin_space_left`, but just `auditd_space_left` The admin value should is defined as : 

> 
> admin_space_left
>     This is a numeric value in megabytes that tells the audit daemon when to perform a configurable action because the system is running low on disk space. This should be considered the last chance to do something before running out of disk space. **The numeric value for this parameter should be lower than the number for space_left.**

Therefore ; 

```
- name: assert | Test auditd_admin_space_left
  ansible.builtin.assert:
    that:
      - auditd_admin_space_left is defined
      - auditd_admin_space_left is number
      - auditd_admin_space_left >= 0
      - auditd_admin_space_left <= auditd_space_left
    quiet: true
```
and, 

```
- name: assert | Test auditd_space_left
  ansible.builtin.assert:
    that:
      - auditd_space_left is defined
      - auditd_space_left is number or  auditd_space_left is string
      - auditd_space_left is match("([0-9])+%*")
    quiet: true

```

Should be correct. See merge
